language: python
python:
  - "3.6"
before_install:
  - python3 -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
script:
  - pytest --cov=src tests
after_success:
  - codecov